export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type UserRole = 'admin' | 'agent';
export type UnitStatus = 'Available' | 'Reserved' | 'Sold';
export type UnitCategory = 'sales' | 'rent';
export type TaskPriority = 'urgent' | 'high' | 'medium' | 'low';
export type TaskStage = 'todo' | 'in_progress' | 'review' | 'done';
export type LeadStatus = 'New' | 'Contacted' | 'ViewingScheduled' | 'Negotiating' | 'Won' | 'Lost';
export type ContractStatus = 'draft' | 'pending_approval' | 'signed' | 'completed' | 'cancelled';
export type InteractionType = 'call' | 'whatsapp' | 'meeting' | 'viewing' | 'offer' | 'note' | 'contract';
export type AppointmentStatus = 'scheduled' | 'completed' | 'cancelled' | 'no_show';

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          email: string | null;
          phone: string | null;
          role: UserRole;
          avatar_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          email?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string | null;
          phone?: string | null;
          role?: UserRole;
          avatar_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      units: {
        Row: {
          id: string;
          status: UnitStatus;
          category: UnitCategory;
          compound: string;
          area: string;
          property_type: string;
          unit_type: string;
          size: number;
          beds: number;
          baths: number;
          floor: string | null;
          price: number;
          currency: string;
          notes: string | null;
          owner_name: string | null;
          owner_phone: string | null;
          delivery_date: string | null;
          agent_name: string | null;
          assigned_agent_id: string | null;
          images: Json;
          video_url: string | null;
          qr_code_url: string | null;
          is_published_landing: boolean;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          status?: UnitStatus;
          category?: UnitCategory;
          compound: string;
          area: string;
          property_type?: string;
          unit_type?: string;
          size?: number;
          beds?: number;
          baths?: number;
          floor?: string | null;
          price?: number;
          currency?: string;
          notes?: string | null;
          owner_name?: string | null;
          owner_phone?: string | null;
          delivery_date?: string | null;
          agent_name?: string | null;
          assigned_agent_id?: string | null;
          images?: Json;
          video_url?: string | null;
          qr_code_url?: string | null;
          is_published_landing?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          status?: UnitStatus;
          category?: UnitCategory;
          compound?: string;
          area?: string;
          property_type?: string;
          unit_type?: string;
          size?: number;
          beds?: number;
          baths?: number;
          floor?: string | null;
          price?: number;
          currency?: string;
          notes?: string | null;
          owner_name?: string | null;
          owner_phone?: string | null;
          delivery_date?: string | null;
          agent_name?: string | null;
          assigned_agent_id?: string | null;
          images?: Json;
          video_url?: string | null;
          qr_code_url?: string | null;
          is_published_landing?: boolean;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      unit_comments: {
        Row: {
          id: string;
          unit_id: string;
          author_id: string | null;
          author_name: string;
          author_role: string | null;
          content: string;
          is_pinned: boolean;
          pinned_at: string | null;
          category: string;
          tags: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          unit_id: string;
          author_id?: string | null;
          author_name: string;
          author_role?: string | null;
          content: string;
          is_pinned?: boolean;
          pinned_at?: string | null;
          category?: string;
          tags?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          unit_id?: string;
          author_id?: string | null;
          author_name?: string;
          author_role?: string | null;
          content?: string;
          is_pinned?: boolean;
          pinned_at?: string | null;
          category?: string;
          tags?: Json;
          created_at?: string;
          updated_at?: string;
        };
      };
      unit_audit_logs: {
        Row: {
          id: string;
          unit_id: string;
          action: string;
          field: string | null;
          old_value: string | null;
          new_value: string | null;
          changed_by_id: string | null;
          changed_by_name: string;
          notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          unit_id: string;
          action: string;
          field?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          changed_by_id?: string | null;
          changed_by_name: string;
          notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          unit_id?: string;
          action?: string;
          field?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          changed_by_id?: string | null;
          changed_by_name?: string;
          notes?: string | null;
          created_at?: string;
        };
      };
      clients: {
        Row: {
          id: string;
          name: string;
          phone: string;
          phone2: string | null;
          email: string | null;
          preferred_area: string | null;
          property_type: string | null;
          budget_min: number | null;
          budget_max: number | null;
          currency: string;
          status: LeadStatus;
          priority: TaskPriority;
          notes: string | null;
          assigned_agent_id: string | null;
          assigned_agent_name: string | null;
          last_contact_date: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          phone2?: string | null;
          email?: string | null;
          preferred_area?: string | null;
          property_type?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          currency?: string;
          status?: LeadStatus;
          priority?: TaskPriority;
          notes?: string | null;
          assigned_agent_id?: string | null;
          assigned_agent_name?: string | null;
          last_contact_date?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          phone2?: string | null;
          email?: string | null;
          preferred_area?: string | null;
          property_type?: string | null;
          budget_min?: number | null;
          budget_max?: number | null;
          currency?: string;
          status?: LeadStatus;
          priority?: TaskPriority;
          notes?: string | null;
          assigned_agent_id?: string | null;
          assigned_agent_name?: string | null;
          last_contact_date?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      client_interactions: {
        Row: {
          id: string;
          client_id: string;
          unit_id: string | null;
          type: InteractionType;
          agent_id: string | null;
          agent_name: string;
          summary: string;
          outcome: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          unit_id?: string | null;
          type?: InteractionType;
          agent_id?: string | null;
          agent_name: string;
          summary: string;
          outcome?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          client_id?: string;
          unit_id?: string | null;
          type?: InteractionType;
          agent_id?: string | null;
          agent_name?: string;
          summary?: string;
          outcome?: string | null;
          created_at?: string;
        };
      };
      tasks: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          assigned_to_id: string | null;
          assigned_to_name: string | null;
          due_date: string | null;
          due_time: string | null;
          priority: TaskPriority;
          stage: TaskStage;
          related_unit_id: string | null;
          related_client_id: string | null;
          is_completed: boolean;
          completed_at: string | null;
          subtasks: Json;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          assigned_to_id?: string | null;
          assigned_to_name?: string | null;
          due_date?: string | null;
          due_time?: string | null;
          priority?: TaskPriority;
          stage?: TaskStage;
          related_unit_id?: string | null;
          related_client_id?: string | null;
          is_completed?: boolean;
          completed_at?: string | null;
          subtasks?: Json;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          assigned_to_id?: string | null;
          assigned_to_name?: string | null;
          due_date?: string | null;
          due_time?: string | null;
          priority?: TaskPriority;
          stage?: TaskStage;
          related_unit_id?: string | null;
          related_client_id?: string | null;
          is_completed?: boolean;
          completed_at?: string | null;
          subtasks?: Json;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      contracts: {
        Row: {
          id: string;
          unit_id: string;
          buyer_name: string;
          buyer_phone: string;
          seller_name: string;
          seller_phone: string;
          sales_price: number;
          down_payment: number;
          installment_amount: number;
          installment_years: number;
          commission_rate: number;
          commission_amount: number;
          agent_share: number;
          company_share: number;
          contract_date: string;
          status: ContractStatus;
          assigned_agent_id: string | null;
          assigned_agent_name: string | null;
          notes: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          unit_id: string;
          buyer_name: string;
          buyer_phone: string;
          seller_name: string;
          seller_phone: string;
          sales_price: number;
          down_payment?: number;
          installment_amount?: number;
          installment_years?: number;
          commission_rate?: number;
          commission_amount?: number;
          agent_share?: number;
          company_share?: number;
          contract_date?: string;
          status?: ContractStatus;
          assigned_agent_id?: string | null;
          assigned_agent_name?: string | null;
          notes?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          unit_id?: string;
          buyer_name?: string;
          buyer_phone?: string;
          seller_name?: string;
          seller_phone?: string;
          sales_price?: number;
          down_payment?: number;
          installment_amount?: number;
          installment_years?: number;
          commission_rate?: number;
          commission_amount?: number;
          agent_share?: number;
          company_share?: number;
          contract_date?: string;
          status?: ContractStatus;
          assigned_agent_id?: string | null;
          assigned_agent_name?: string | null;
          notes?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      owners: {
        Row: {
          id: string;
          name: string;
          phone: string;
          phone2: string | null;
          whatsapp: string | null;
          email: string | null;
          area: string | null;
          address: string | null;
          company: string | null;
          notes: string | null;
          assigned_agent_id: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          phone2?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          area?: string | null;
          address?: string | null;
          company?: string | null;
          notes?: string | null;
          assigned_agent_id?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          phone2?: string | null;
          whatsapp?: string | null;
          email?: string | null;
          area?: string | null;
          address?: string | null;
          company?: string | null;
          notes?: string | null;
          assigned_agent_id?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          title: string;
          unit_id: string | null;
          client_id: string | null;
          agent_id: string | null;
          agent_name: string | null;
          appointment_date: string;
          start_time: string;
          end_time: string | null;
          status: AppointmentStatus;
          location: string | null;
          notes: string | null;
          is_demo: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          unit_id?: string | null;
          client_id?: string | null;
          agent_id?: string | null;
          agent_name?: string | null;
          appointment_date: string;
          start_time: string;
          end_time?: string | null;
          status?: AppointmentStatus;
          location?: string | null;
          notes?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          unit_id?: string | null;
          client_id?: string | null;
          agent_id?: string | null;
          agent_name?: string | null;
          appointment_date?: string;
          start_time?: string;
          end_time?: string | null;
          status?: AppointmentStatus;
          location?: string | null;
          notes?: string | null;
          is_demo?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_admin: {
        Args: Record<PropertyKey, never>;
        Returns: boolean;
      };
    };
    Enums: {
      user_role: UserRole;
      unit_status: UnitStatus;
      unit_category: UnitCategory;
      task_priority: TaskPriority;
      task_stage: TaskStage;
      lead_status: LeadStatus;
      contract_status: ContractStatus;
      interaction_type: InteractionType;
      appointment_status: AppointmentStatus;
    };
  };
}
